name: 'asyncapi-github-action'
author: 'Waleed Ashraf'
description: 'Github Action for AsyncAPI schema validation'
inputs:
  sc:
    filepath: 'Path of asyncapi schema file'
    required: true
    default: './asyncapi.yaml'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'file-text'
  color: 'blue'
