name: 'asyncapi-github-action'
author: 'Waleed Ashraf'
description: 'Github Action for AsyncAPI schema validation'
inputs:
  filepath:
    description: 'Path of asyncapi schema file'
    required: true
    default: 'asyncapi.yaml'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'file-text'
  color: 'blue'
