name: "tests"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
      - run: npm test
  validate-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: asyncapi-github-action
        uses: ./
        with:
          filepath: './test/mock-schema.yaml'
